package com.cross.enumtype;

/**
 *      * 任务完成动作 PERFECT_INFORMATION 完善信息；AUTH_SUCCESS_EXPERT 认证成功1个渠道达人,AUTH_SUCCESS_UPGRADE_EXPERT 认证成功升级1个渠道达人 ,OPNE_DISTRIBUTER 开通合伙人权益,UPGRADE_EXPERT_DISTRIBUTER 升级成为高级合伙人,FINISH_ONE_PROMOTION_TASK 完成1个推广任务, BUY_PLATFORM_PRODUCTS 完成1次平台商品自购买消费,SUCCESS_DISTRIBUTER_SELF_PRODUCTS 成功分销1次自营商品
 * The IslandTask enumeration.
 */
public enum IslandTask {
    UP_THE_GRADE,PERFECT_INFORMATION, AUTH_SUCCESS_EXPERT, AUTH_SUCCESS_UPGRADE_EXPERT, OPNE_DISTRIBUTER, UPGRADE_EXPERT_DISTRIBUTER, FINISH_ONE_PROMOTION_TASK, BUY_PLATFORM_PRODUCTS, SUCCESS_DISTRIBUTER_SELF_PRODUCTS
}
